# -*- coding: utf-8 -*-
"""

Analysis code which takes the trajectories generated by Particle Tracker and 
links these short trajectories into longer ones using Hierarchical Clustering
Methods. 

@author: Alec Meacham and Han Yang
"""

"""

Imports

"""

import os
import csv

import numpy as np
from numpy.linalg import eig
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.offsetbox import AnchoredText

from scipy.cluster.hierarchy import linkage
from sklearn.cluster import AgglomerativeClustering
from scipy import stats

"""

Define Methods

"""

def log_input(log_path, print_statement):

    """ 
    Print instruction, gather user input and write program output into a 
    log.txt file. 
    
    Args: 
        log_path: (str) Filepath where the log.txt file is located
        print_statement: (str) Prompt displayed to the user
        
    Returns:
        input_val: (str) User input value
    """

    input_val = input(print_statement)

    logFile = open(log_path, 'a')
    logFile.write(print_statement + input_val + '\n\n')
    logFile.close()

    return input_val

def create_saveto_filepath(filepath, new_end):

    """
    Create a new filepath for saving output files
    
    Args: 
        filepath: (str) Filepath of original input as a base for appending
        new_end: (str) String to append to the end of the original filepath
    
    Returns: 
        save_to_filepath: (str) Filepath with newly appended ending
    """
    
    save_to_filepath = filepath.replace('.txt', new_end)

    return save_to_filepath

def inputs():
    
    """
    Prompt user to input filepaths and how the trajectories were originally
    generated. 
    
    Args:
        None
        
    Returns:
        filename: (str) Filepath of input trajectories
        foldername: (str) Folder where all files will be written
        log_path: (str) Filepath where the log.txt file is located
        movie_len: (int) Number of frames in movie
        tbf: (float) Time between Frames of Movie
        pixel_size: (int) Pixel size (nm)
        MSD_pts: (int) Number of MSD pts to fit for Dmsd calculation. 
        t_tot: (int) Normlaization time for radius of gyration calculation
        
    """
    
    filename = input("Input filepath:\n")
    filepath_tuple = filename.rpartition('\\')
    foldername = filepath_tuple[0]
    
    log_path = foldername + r'\log.txt'
    logFile = open(log_path, 'w')
    logFile.write('Filepath: ' + filename + '\n\n')
    logFile.close()
    
    movie_len = int(log_input(log_path, "What is the movie length (frames)?\n"))
    tbf = float(log_input(log_path, "What is the TBF(s)?\n"))
    # min_trajlen = int(log_input(log_path, "What is the minimum trajectory length allowed for a trajectory to do clustering?\n"))
    pixel_size = int(log_input(log_path, "What is your pixel size (nm)?\n"))
    
    MSD_pts = int(log_input(log_path, "How many MSD points would you like to fit through?\n"))
    
    t_tot = int((log_input(log_path, 'What time (s) would you like to normalize Rg trajectories to?\n')))
    
    return filename, foldername, log_path, movie_len, tbf, pixel_size, MSD_pts, t_tot

def format_trajs(filename):

    """
    Formats trajectories from Particle Tracker in a way that is easily
    viewable in Excel. 'sfe' = safe for Excel
    
    Args: 
        filename: (str) Filepath location of input trajectories
        
    Returns:
        outname: (str) Filepath of '_sfe' formatted trajectories
    """
    
    out = []
    with open(filename) as file:
        for line in file:
            if "score" in line:
                for line in file:
                    pass # This is to pass the following empty line after "score"
                    for line in file:
                        if "%%" in line:
                            pass
                        else:
                            out.append(line)
                            
    outname = create_saveto_filepath(filename, '_sfe.txt')
    outfile = open(outname, "w+")
    outfile.writelines(out[:-1])
    outfile.close()
    
    return outname

def create_dataframe(trajs):
    
    """
    Create a pandas data frame with all trajectories
    
    Args:
        trajs: (List) List of all input trajectories
        
    Returns: df_raw (Dataframe) Data frame containing all input trajectories
    """
    
    print("Generating Dataframes... \n\n")
    
    row = {
        "id": 0,
        "frame_index": 0,
        "x": 0.0,
        "y": 0.0,
        }
    
    # Create Row List
    
    row_list = []
    row_id = 0
    
    for line in trajs:
        if len(line) != 0:
            row["id"] = row_id
            row["frame_index"] = int(line[0])
            row["x"] = float(line[1])
            row["y"] = float(line[2])
            
            new_row = dict(row)
            row_list.append(new_row)
            
        else:
            row_id += 1
            
    # Append to DataFrame at Once!
    
    df_raw = pd.DataFrame(row_list, columns=['frame_index', 'x', 'y', 'id'])
    df_raw.id.value_counts()
    # df = df_raw[df_raw['id'].map(df_raw['id'].value_counts()) >= min_trajlen] # Filter trajlen > min_trajlen
    
    return df_raw

def hierarchical_clustering(df_raw, foldername):
    
    """
    Links short trajectories from Particle Tracker using Hierarchical Clustering
    methods. 
    
    Args:
        df_raw: (Dataframe) Data frame containing all input trajectories
        foldername: (str) Folder where all files will be written
        
    Returns: 
        df: (Dataframe) Dataframe containing all linked trajectories
        coordinates: (Dataframe) Dataframe of average xy-coordinates for each 
            short input trajectory
        hc: (object) Output of scikit-learn Agglomerative Clustering method
        centers: (Dataframe) Dataframe of average xy-coordiantes for each 
            clustered trajectory
        df_short: (Dataframe) Dataframe containing all clustered trajectories 
            which are shorter than the user specified minimum trajectory length
        coordinates_short: (Dataframe) Dataframe containing all average xy-
            coordiantes for each clustered trajectory shorter than the user
            specified minimum trajectory length
        num_clusters: (int) Number of clusters found
        min_trajlen: (int) Minimum number of frames that a trajectory must be to
            be considered significant
    """
    
    print("Performing Clustering...\n\n")
    
    cluster_good = "N"
    while cluster_good != "Y":
    
        min_trajlen = int(log_input(log_path, "What is the minimum trajectory length allowed for a trajectory to do clustering?\n"))    
    
        df = df_raw[df_raw['id'].map(df_raw['id'].value_counts()) >= min_trajlen] # Filter trajlen > min_trajlen
        coordinates = df.groupby(['id'])[['x', 'y']].mean()    
    
        link = linkage(coordinates, method='complete')
        
        # Find the threshold number of pixels for clustering
        
        threshold_pixel_range = np.arange(0.1, 5, 0.1)
        threshold_num_clusters_range = np.zeros(len(threshold_pixel_range))
        for i in range(len(threshold_pixel_range)):
            threshold_num_clusters_range[i] = len(link[link[:, 2] >= threshold_pixel_range[i]]) + 1
            
        plt.figure()
        plt.title('Pixel Threshold')
        plt.xlabel('Pixel')
        plt.ylabel('Number of Clusters')
        plt.scatter(threshold_pixel_range, threshold_num_clusters_range, marker='.')
        plt.savefig(create_saveto_filepath(filename, '_pixel_threshold.png'))
        plt.show()
        plt.close()
        
        cluster_good = log_input(log_path, "Is this clustering good?\n").capitalize()
        
    pixel_threshold = float(log_input(log_path, "How many pixels will you allow for linkage?\n"))
        
    num_clusters = len(link[link[:, 2] >= pixel_threshold]) + 1
    
    if len(link) - num_clusters < 0:
        print("No linking below this pixel threshold.\n"
              "Use Pixel threshold instead of linkage distance for later short traj linking\n")
        linkage_distance = pixel_threshold
    else: 
        linkage_distance = link[len(link) - num_clusters, 2]
        
    print("\nNumber of Clusters: ", num_clusters)
    print("Linkage Distance: ", linkage_distance, "\n")
    
    hc = AgglomerativeClustering(n_clusters=num_clusters, metric='euclidean', linkage='complete')
    hc_labels = hc.fit_predict(coordinates)
    coordinates['hc_label'] = hc_labels
    
    centers = coordinates.groupby(['hc_label'])[['x', 'y']].mean()
    centers_filepath = create_saveto_filepath(filename, '_centers.csv')
    np.savetxt(centers_filepath, centers, delimiter=',')
    
    # Add short trajectories
    
    df_short = df_raw[df_raw['id'].map(df_raw['id'].value_counts()) <= min_trajlen]
    
    coordinates_short = df_short.groupby(['id'])[['x', 'y']].mean()
    coordinates_short_arr = coordinates_short.to_numpy()
    coordinates_short['hc_label'] = 0
    
    for i in range(num_clusters):
        distance = (coordinates_short_arr[:, 0] - centers['x'][i]) ** 2 + (coordinates_short_arr[:, 1] - centers['y'][i]) ** 2 < (linkage_distance / 2) ** 2
    
        mask_1 = np.logical_xor(coordinates_short['hc_label'], distance)
        mask_2 = np.logical_and(distance, mask_1)
        coordinates_short['hc_label'] += mask_2 * (i + 1)
        
    coordinates_short['hc_label'] -= 1
    
    print("Clustering Complete! \n")
                
    return df, coordinates, hc, centers, df_short, coordinates_short, num_clusters, min_trajlen

def format_traj(df_raw, coordinates, coordinates_short, movie_len, num_clusters):
    
    """
    Formats trajectories output from hierarchical clustering
    
    Args: 
        df_raw: (Dataframe) Data frame containing all input trajectories
        coordinates: (Dataframe) Dataframe of average xy-coordinates for each 
            short input trajectory
        coordinates_short: (Dataframe) Dataframe containing all average xy-
            coordiantes for each clustered trajectory shorter than the user
            specified minimum trajectory length
        movie_len: (int) Number of frames in movie
        num_clusters: (int) Number of clusters found
        
    Returns: 
        traj_array: (ndarray (movie_len, num_clusters*2)) Hierarchically
            clustered trajectories for each molecule whose linked
            trajectories met the user specified requirements
        
    """
    
    linked_traj_list = list()
    linked_traj_len_list = list()
    
    traj_array = np.zeros((movie_len, num_clusters*2))
    
    for i in range(num_clusters):
        linked_traj_long = pd.concat([df_raw[df_raw.id.isin(coordinates.index[coordinates['hc_label'] == i])]])
        linked_traj_short = pd.concat([df_raw[df_raw.id.isin(coordinates_short.index[coordinates_short['hc_label'] == i])]])
        linked_traj = pd.concat([linked_traj_long, linked_traj_short])
    
        linked_traj = linked_traj.sort_values(by=['id', 'frame_index'])
        linked_traj_list.append(linked_traj)
        linked_traj_len_list.append((len(linked_traj)))
    
        traj_mask = pd.DataFrame(np.nan, index=range(movie_len), columns=['x', 'y'])
        traj = linked_traj_list[i].set_index('frame_index')
        traj_filtered = traj[~traj.index.duplicated()] # filter the duplicated frame_index
        masked_traj = traj_filtered.reindex_like(traj_mask)
        traj_array[:, i*2:i*2+2] = masked_traj.to_numpy()
    
    trajarr_filepath = create_saveto_filepath(filename, '_raw_trajectories.csv')
    np.savetxt(trajarr_filepath, traj_array, delimiter=',')
    
    return traj_array

def plot_trajpts(traj, index):
    
    """
    Plot xy-trajectories for each molecule with time represented by 
    the color gradient
    
    Args:
        traj: (ndarray (movie_len, 2)) xy-trajectory of a single molecule 
        index: (int) Index of molecule being plotted
        
    Returns: 
        None
    """
    
    # Create a folder for saving graphs
    new_folder = folder + '\position_graphs'
    
    if index == 0:
        try:
            os.mkdir(new_folder)
        except OSError:
            print('Failed to create directory for Position graphs. Folder likely already exists.\n')
        else:
            print('Created directory for Position graphs. Now calculating fits...\n')
        
    # Select Data
    xdata = traj[:, 0]
    ydata = traj[:, 1]
    
    num_pts = traj.shape[0] 
    x = np.linspace(-1, 1, num_pts)
    cmap = np.tan(x)
    
    # Generate Graph
    graph_file = new_folder + '/Trajectory' + str(index+1) + '.jpg'
    title = 'Trajectory ' + str(index+1)
    
    scatters = plt.scatter(xdata, ydata, c=np.arange(num_pts), marker='.', label='XY-positions')
    
    plt.xlabel('X-pixel Coordinate')
    plt.ylabel('Y-pixel Coordinate')
    plt.xticks(rotation=45)
    plt.axis('equal')
    plt.gca().invert_yaxis()
    
    plt.title(title)
    plt.legend()
    plt.colorbar(scatters, label="Traj. Frame")
    
    plt.gcf().subplots_adjust(bottom=0.20)
    plt.savefig(graph_file, dpi=300)
    
    if index == 0: 
        plt.show()
    
    plt.close()
        
    return

def filter_trajectories(traj_arr, num_clusters, num_frames):
    
    """
    Filter Trajectories based on the total number of tracked frames
    when all short trajectories for a molecule are clustered together
    
    Args: 
        traj_arr: (ndarray (movie_len, num_clusters*2)) Hierarchically
            clustered trajectories for each molecule whose linked
            trajectories met the user specified requirements
        num_clusters: (int) Number of clusters found
        num_frames: (int) Number of frames in movie
        
    Returns:
        goodtrajct: (int) Number of trajectories which exceed the specified
            minimum number of frames tracked
        filtered_trajarr: (ndarray (movie_len, goodtrajct*2)) All molecule
            trajectories which exceed the specified minimum number of frames
            tracked. NaN indicate frames for which the molecule could not be
            localized. 
        good_trajinfo: (ndarray, (goodtrajct, 4)): Array with per-trajectory
            information including: 
                - Number of positions tracked
                - Trajectory length (last frame - first frame)
                - Initial frame localized
                - Final frame localized
    """
    
    for i in range(num_clusters):
        
        traj = traj_arr[:, i*2:i*2+2]
        plot_trajpts(traj, i)
    
    num_pos = np.zeros(num_clusters)
    init_frame = np.zeros(num_clusters)
    fin_frame = np.zeros(num_clusters)
    traj_len = np.zeros(num_clusters)

    # Plot trajectory graphs and compute number of tracked frames and length from initial-to-final tracked frame
    for i in range(num_clusters):
        traj = traj_arr[:, i*2:i*2+2]
        num_pos[i] = np.count_nonzero(~np.isnan(traj[:, 0]))    # Shouldn't matter if you check NaN for X or Y coordinate
        
        for j in range(num_frames):
            if ~np.isnan(traj[j, 0]):
                init_frame[i] = j+1
                break
            
        for j in range(num_frames):
            if ~np.isnan(traj[num_frames-j-1, 0]):
                fin_frame[i] = num_frames-j
                break
                
        traj_len = fin_frame - init_frame
    
    traj_info = np.zeros((num_clusters, 4))
    traj_info[:, 0] = num_pos
    traj_info[:, 1] = traj_len 
    traj_info[:, 2] = init_frame
    traj_info[:, 3] = fin_frame
    
    trajinfo_filepath = create_saveto_filepath(filename, '_raw_trajinfo.csv')
    np.savetxt(trajinfo_filepath, traj_info, delimiter=',', header='NumPts, TrajLen, InitFrame, FinFrame')
    
    # Graph Number of Positions Tracked versus Length
    
    x_data = traj_len
    y_data = num_pos
    
    fig, ax = plt.subplots(1,1)
    plt.scatter(x_data, y_data, marker='.')
    
    plt.title("Trajectory Info")
    plt.xlabel('Trajectory Length (Final Frame - Initial Frame Tracked')
    plt.ylabel('Number of Tracked Positions')
    
    txt_str = 'Number of Trajectories Represented: ' + str(y_data.shape[0])
    
    at = AnchoredText(txt_str, prop=dict(size=12), frameon=True, loc='upper left')
    at.patch.set_boxstyle("round, pad=0., rounding_size=0.2")
    ax.add_artist(at)
    
    plt.savefig(create_saveto_filepath(filename, '_raw_trajinfo.jpg'), dpi=300)
    plt.show()
    plt.close()
    
    # Apply a Filter to Trajectory based on Number of Tracked Positions
    
    filter_good = 'N' #log_input(log_path, "Are the unfiltered trajectories sufficient? (Y/N)\n").capitalize()
    while filter_good != 'Y':
        posct_cutoff = float(log_input(log_path, "What cutoff would you like to apply to the number of tracked positions?\n"))
    
        goodct = 0
        for i in range(num_clusters):
            if num_pos[i] > posct_cutoff:
                goodct += 1
                
                if goodct == 1:
                    good_trajinfo = [traj_info[i, :]]
                    goodtrajidx = [i]
                    
                else: 
                    good_trajinfo = np.append(good_trajinfo, [traj_info[i, :]], axis=0)
                    goodtrajidx = np.append(goodtrajidx, [i], axis=0)
    
        good_trajinfo_filepath = create_saveto_filepath(filename, '_filtered_trajinfo.csv')
        np.savetxt(good_trajinfo_filepath, good_trajinfo, delimiter=',', header='NumPts, TrajLen, InitFrame, FinFrame')
        
        # Graph Number of Positions Tracked versus Length for Filtered Data
        
        x_data = good_trajinfo[:, 1]
        y_data = good_trajinfo[:, 0]
        
        fig, ax = plt.subplots(1,1)
        plt.scatter(x_data, y_data, marker='.')
        
        plt.title("Trajectory Info")
        plt.xlabel('Trajectory Length (Final Frame - Initial Frame Tracked')
        plt.ylabel('Number of Tracked Positions')
        
        txt_str = 'Number of Trajectories Represented: ' + str(y_data.shape[0])
        
        at = AnchoredText(txt_str, prop=dict(size=12), frameon=True, loc='upper left')
        at.patch.set_boxstyle("round, pad=0., rounding_size=0.2")
        ax.add_artist(at)
        
        hline_label = "Tracked Position Cutoff" + str(posct_cutoff)
        plt.axhline(y = posct_cutoff, color = 'r', linestyle="--", label=hline_label)
        
        plt.savefig(create_saveto_filepath(filename, '_filtered_trajinfo.jpg'), dpi=300)
        plt.show()
        plt.close()
        
        filter_good = log_input(log_path, "Is this filtering of trajectories sufficient? (Y/N)\n").capitalize()
    
    # Filter Trajectories based on Applied Cutoff
    goodtrajct = goodtrajidx.shape[0]
    filtered_trajarr = np.zeros((num_frames, goodtrajct*2))
    for i in range(goodtrajct):
        goodidx = goodtrajidx[i]
        filtered_trajarr[:, 2*i:2*i+2] = traj_arr[:, 2*goodidx:2*goodidx+2]
        
    filtered_traj_filepath = create_saveto_filepath(filename, '_filtered_trajectories.csv')
    goodtraj_filepath = create_saveto_filepath(filename, '_filtered_trajectories_indices.csv')
    np.savetxt(filtered_traj_filepath, filtered_trajarr, delimiter=',')
    np.savetxt(goodtraj_filepath, goodtrajidx, delimiter=',')
    
    return goodtrajct, filtered_trajarr, good_trajinfo

def MSD(traj, MSD_pts):
    
    """
    Computes mean-squared displacement (nm^2) for each trajectory
    
    Args: 
        traj: (ndarray (movie_len, 2)) xy-trajectory of a single molecule 
        MSD_pts: (int) Number of MSD pts to fit for Dmsd calculation
        
    Returns:
        msd_arr: (ndarray (MSD_pts,)) List of each lag-time MSD value for
            the input trajectory
        msd_count_array: (ndarray (MSD_pts,)) List of the number of non-NaN 
            lag-times used to compute each MSD point
    """
    
    msd_arr = np.zeros((MSD_pts, ))
    msd_count_arr = np.zeros((MSD_pts, ))
    
    """ Calculate MSD """
    
    for i in range(MSD_pts):
        
        frame_offset = i+1
        step = np.zeros((traj.shape[0] - frame_offset, 1))
        
        for j in range(traj.shape[0] - frame_offset):
            
            x_step = (traj[j + frame_offset, 0] - traj[j, 0]) * pixel_size
            y_step = (traj[j + frame_offset, 1] - traj[j, 1]) * pixel_size
            
            step[j] = np.sqrt(np.power(x_step, 2) + np.power(y_step, 2))
            
        msd_arr[i] = np.nanmean(step[:] ** 2)
        msd_count_arr[i] = np.count_nonzero(~np.isnan(step)) # Count how many non NaN steps are averaged
    
    return msd_arr, msd_count_arr

def DMSD(msd, MSD_pts, tbf, folder):
    
    """
    Compute diffusion coefficient by fitting MSD points to a line
    
    Args: 
        msd: (ndarray (MSD_pts, goodtrajct)) Array of all trajectories MSD 
            values
        MSD_pts: (int) Number of MSD pts to fit for Dmsd calculation. 
        tbf: (float) Time between Frames of Movie
        folder: (str) Folder where all files will be written
        
    Returns: 
        Dmsd_arr: (ndarray (goodtrajct, 3)) Dmsd, fit intercept and fit r^2
            values
    """
    
    # Make folder
    Dmsd_folder = folder + '\Dmsd_fit_graphs'
    
    try:
        os.mkdir(Dmsd_folder)
    except OSError:
        print('Failed to create directory for Dmsd fit graphs. Folder likely already exists.\n')
    else:
        print('Created directory for Dmsd fit graphs. Now calculating fits...\n')
    
    # Compute
    x_data = (np.arange(MSD_pts) + 1) * tbf
    
    for i in range(msd.shape[1]):
        y_data = msd[:, i]
        res = stats.linregress(x_data, y_data)
        
        Dmsd_arr[i, 0] = res.slope / 4
        Dmsd_arr[i, 1] = res.intercept
        Dmsd_arr[i, 2] = res.rvalue ** 2
    
        # Plots Fits
        graph_file = Dmsd_folder + '/feature' + str(i+1) + '.jpg'
        title = 'Feature ' + str(i + 1)
        fig, ax = plt.subplots(1, 1)
        
        plt.scatter(x_data, y_data, label='MSD Points')
        plt.plot(x_data, res.intercept + res.slope*x_data, 'r', label='Dmsd Fit')
        
        plt.xlabel('Time Lag (s)')
        plt.ylabel('MSD')
        plt.title(title)
    
    
        txt_str = 'm =' + str(res.slope)[0:5] + '\n' + 'b =' + str(res.intercept)[0:5] + '\n' + r'$r^{2} =$' + str(res.rvalue**2)[0:5]
        
        at = AnchoredText(txt_str, prop=dict(size=12), frameon=True, loc='lower right')
        
        at.patch.set_boxstyle("round, pad=0., rounding_size=0.2")
        ax.add_artist(at)
        
        plt.savefig(graph_file, dpi=300)
    
        # Display the first 5 graphs for reference during analysis
        if i == 0:
            print('\n Feature', i + 1, 'results: \n')
            plt.show()
            print('\nSaving all graphs... Please wait...\n')
    
        plt.close()
    
    return Dmsd_arr

def Rg_a2_calc(traj, tbf, t_tot):
    
    """
    Compute Radius of Gyration (Rg) and asymmetry coefficient (a2) via the
    radius of gyration tensor
    
    Args: 
        traj: (ndarray (movie_len, 2)) xy-trajectory of a single molecule
        tbf: (float) Time between Frames of Movie
        t_tot: (int) Normlaization time for radius of gyration calculation
        
    Returns: 
        Rg: (float) Radius of gyration
        Rg_norm: (float) Time-normalized Radius of gyration
        a2: (float) Asymmetry coefficient
        R1_squared: (float) One eigenvalue of the radius of gyration tensor
        R2_squared: (float) The other eigenvalue of the radius of gyration
            tensor
        N: (int) Number of positions tracked in the trajectory
        first_frame: (int) First frame localized
        last_frame: (int) Last frame localized
    """
    
    # Initialize Variables
    
    tensor = np.zeros((2, 2))
    
    avg_x = np.nanmean(traj[:, 0])
    avg_y = np.nanmean(traj[:, 1])
    
    """ Approach 1: Calculate with N = last frame tracked - first frame tracked """
    """ This approach over estimates the number of positions and thus tracjectories with a smaller
    percentage of tracked positions vs total timesteps yield lower Rg """
    
    # first_frame = np.argmax(~np.isnan(traj[:, 0]))
    # last_frame = np.argwhere(~np.isnan(traj[:, 0]))[-1][0]
    
    # N = last_frame - first_frame
    
    # if N == 0:
    #     return np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan
    
    """ Approach 2: Calculate with N = number positions tracked (i.e.; number of non NaNs) """
    """ This approach should more accurately reperesent the number of positions tracked but may
    in part misrepresent the total time of a trajectory i.e., this method is treating a trajectory
    of length 30 where every frame is tracked the same as a tracjectory of length 100 where only
    30 total frames are tracked """
    
    first_frame = np.argmax(~np.isnan(traj[:, 0]))
    last_frame = np.argwhere(~np.isnan(traj[:, 0]))[-1][0]
    
    N = np.count_nonzero(~np.isnan(traj))
    if N == 0:
        return np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan
    
    # Calculate the Tensor ************************
    
    tensor[0, 0] = (1 / N) * np.nansum((traj[:, 0] - avg_x)**2)
    tensor[0, 1] = (1 / N) * np.nansum((traj[:, 0] - avg_x) * (traj[:, 1] - avg_y))
    tensor[1, 0] = (1 / N) * np.nansum((traj[:, 0] - avg_x) * (traj[:, 1] - avg_y))
    tensor[1, 1] = (1 / N) * np.nansum((traj[:, 1] - avg_y)**2)
    
    # Calculate the Eigen Values **************************
    
    eig_vals, eig_vec = eig(tensor)
    
    R1_squared = eig_vals[0]
    R2_squared = eig_vals[1]
    
    # Unit Conversions *********************************
    
    # t_traj = N * tbf
    
    """ Approach 3: Change use approach 2 for tensor calc but change normalization to account for trajectory length """
    
    t_traj = (last_frame - first_frame) * tbf
    
    Rg = np.sqrt(R1_squared + R2_squared) * pixel_size
    Rg_norm = np.sqrt(R1_squared + R2_squared) * np.sqrt(t_tot / t_traj) * pixel_size
    
    # a2 Computation *********************************
    
    if R1_squared > R2_squared:
        a2 = R2_squared / R1_squared
    else:
        a2 = R1_squared / R2_squared
        
    return Rg, Rg_norm, a2, R1_squared, R2_squared, N, first_frame, last_frame

""" 

Old version of Rg Calculation

"""

# def Rg_a2_calc(traj, tbf, t_tot, trajlen):
    
#     """ NOT SURE IF THIS WORKS CAUSE YOU SKIP SO MANY FRAMES; WILL HAVE TO THINK ABOUT MORE """
        
#     tensor = np.zeros((2, 2))
    
#         # N should not be the number of tracked frames, it should be the last frame tracked - the first frame tracked
#     # N = np.count_nonzero(~np.isnan(traj)) # Number of non-NaN elements
    
#     N = trajlen
    
#     avg_x = np.nanmean(traj[:, 0])
#     avg_y = np.nanmean(traj[:, 1])
    
#     # Calculate the tensor
    
#     tensor[0, 0] = (1 / N) * np.nansum((traj[:, 0] - avg_x)**2)
#     tensor[0, 1] = (1 / N) * np.nansum((traj[:, 0] - avg_x) * (traj[:, 1] - avg_y))
#     tensor[1, 0] = (1 / N) * np.nansum((traj[:, 0] - avg_x) * (traj[:, 1] - avg_y))
#     tensor[1, 1] = (1 / N) * np.nansum((traj[:, 1] - avg_y)**2)
    
#     # Calculate Rg and asymmetry (a2)
    
#         # this version was following what Nicki was doing which, as of now (9/21/2023) I *think* is incorrect with regards to what the eigenvalues mean
    
#     # eig_vals, eig_vec = eig(tensor)
#     # R1 = eig_vals[0]    
#     # R2 = eig_vals[1]
    
#     # t_traj = N * tbf
#     # Rg = np.squt(R1**2 + R2**2) * pixel_size
#     # Rg_norm = np.sqrt(R1**2 + R2**2) * np.sqrt(t_tot / t_traj) * pixel_size
    
#     # if R1 > R2:
#     #     a2 = R2**2 / R1**2
#     # else:
#     #     a2 = R1**2 / R2**2
    
#         # this version follows what Flier/Moerner report and I think should be correct (thanks to JDM for pointing out these problems in group meeting)
                
#     eig_vals, eig_vec = eig(tensor)
    
#     R1_squared = eig_vals[0]
#     R2_squared = eig_vals[1]
    
#     t_traj = N * tbf
#     Rg = np.sqrt(R1_squared + R2_squared) * pixel_size
#     Rg_norm = np.sqrt(R1_squared + R2_squared) * np.sqrt(t_tot / t_traj) * pixel_size
    
#     if R1_squared > R2_squared:
#         a2 = R2_squared / R1_squared
#     else:
#         a2 = R1_squared / R2_squared
        
#     return Rg, Rg_norm, a2, R1_squared, R2_squared, N

def output_results(Dmsd_arr, Rg_a2_arr, trajarr, num_feats, folder):
    
    """
    Format and output results file
    
    Args: 
        Dmsd_arr: (ndarray (goodtrajct, 3)) Dmsd, fit intercept and fit r^2
            values
        Rg_a2_arr: (ndarray (goodtrajct, 3)) Array of Rg, Rg_norm and a2 values
        trajarr: (ndarray (movie_len, goodtrajct*2)) Array of all linked 
            particle trajectories
        num_feats: (int) Number of molecules with sufficient linked trajectories
        folder: (str) Folder where all files will be written
        
    Returns: 
        None
    """
    
    num_cols = 10
    results = np.zeros((num_feats, num_cols))
    
    # Compute pixel center positions and take average --> relevant for matching to rotations mostly
    
    pix_ctr = np.empty((movie_len, num_feats*2))
    pix_ctr[:] = np.nan
    
    for i in range(movie_len):
        for j in range(num_feats * 2):
            
            if np.isnan(trajarr[i, j]) == True:
                continue
            
            pix_ctr[i, j] = np.rint(trajarr[i, j])
            
    pixctr_filepath = create_saveto_filepath(filename, '_pixel_centers.csv')
    np.savetxt(pixctr_filepath, pix_ctr, delimiter=',')
    
    for i in range(num_feats):
        x_avg = np.nanmean(pix_ctr[:, i*2])
        y_avg = np.nanmean(pix_ctr[:, i*2+1])
            
        results[i, 0] = y_avg
        results[i, 1] = x_avg
    
    results[:, 2:5] = Dmsd_arr
    with np.errstate(invalid='ignore'):
        results[:, 5] = np.log10(Dmsd_arr[:, 0])
    results[:, 6] = np.sqrt(results[:, 3] / 4)
    results[:, 7:] = Rg_a2_arr
    
    # Add median values nad a line of zeros to the array to delineate
    
    empty_add = np.zeros((2, num_cols))
    results = np.append(empty_add, results, axis=0)
    
    for i in range(results.shape[1]):
        results[0, i] = np.nanmedian(results[2:, i])
    
    results_filepath = create_saveto_filepath(filename, '_translation_results.csv')
    np.savetxt(results_filepath, results, delimiter=',', header='Yavg, Xavg, Dmsd, intercept, R^2, logDmsd, Loc. Unc., Rg, Rg_norm, a2')
    
    print('Median log Dmsd: ' + str(results[0, 5]) + '\nMedian Normalized Rg: ' + str(results[0, 8]) + '\nMedian a2: ' + str(results[0, 9]))
    
    return

def QE_Dmsd(msd_vals, MSD_pts):
    
    """ 
    Compute QE MSD and Fit for Dmsd 
    
    Args: 
        msd_vals: (ndarray (MSD_pts, goodtrajct)) Array of all trajectories MSD 
            values
        MSD_pts: (int) Number of MSD pts to fit for Dmsd calculation.  
        
    Returns: 
        None
    """
    
    QE_Dmsd = np.zeros(3,)
    
    QE_MSD = np.mean(msd_vals, axis=1)
    x_data = (np.arange(MSD_pts) + 1) * tbf
    
    res = stats.linregress(x_data, QE_MSD)
    
    QE_Dmsd[0] = res.slope / 4
    QE_Dmsd[1] = res.intercept
    QE_Dmsd[2] = res.rvalue ** 2

    # Plots Fits
    graph_file = create_saveto_filepath(filename, "_QE_Dmsd_Fit.jpg")
    title = 'QE Dmsd Fit'
    fig, ax = plt.subplots(1, 1)
    
    plt.scatter(x_data, QE_MSD, label='MSD Points')
    plt.plot(x_data, res.intercept + res.slope*x_data, 'r', label='QE Dmsd Fit')
    
    plt.xlabel('Time Lag (s)')
    plt.ylabel('QE MSD')
    plt.title(title)


    txt_str = 'm =' + str(res.slope)[0:5] + '\n' + 'b =' + str(res.intercept)[0:5] + '\n' + r'$r^{2} =$' + str(res.rvalue**2)[0:5]
    
    at = AnchoredText(txt_str, prop=dict(size=12), frameon=True, loc='lower right')
    
    at.patch.set_boxstyle("round, pad=0., rounding_size=0.2")
    ax.add_artist(at)
    
    plt.savefig(graph_file, dpi=300)
    plt.show()
    plt.close()
    
    return

""" 

Run Analysis 

"""

# Load inputs
filename, folder, log_path, movie_len, tbf, pixel_size, MSD_pts, t_tot = inputs()

# Format ImageJ Trajectories and Create Pandas DataFrame
traj_filepath = format_trajs(filename)
with open(traj_filepath) as file:
    reader = csv.reader(file, delimiter=" ")
    lines = list(reader)

df_raw = create_dataframe(lines)
# coordinates = df.groupby(['id'])[['x', 'y']].mean()

# Perform Hierarchical Clustering
df, coordinates, hc, centers, df_short, coordinates_short, num_clusters, min_trajlen = hierarchical_clustering(df_raw, folder)

# Sort Linked Trajectories and Format as Numpy Array will NaN
traj_array = format_traj(df_raw, coordinates, coordinates_short, movie_len, num_clusters)

# Filter Linked Trajectories to Exclude Unwanted Trajectories
goodtrajct, filtered_trajarr, trajinfo = filter_trajectories(traj_array, num_clusters, movie_len)

# Translation Analysis
print("Calculating translational dynamics...\n")

#Calculate MSD
print("Calculating MSD values...\n")
msd_vals = np.zeros((MSD_pts, goodtrajct))
msd_counts = np.zeros((MSD_pts, goodtrajct))

for i in range(goodtrajct):
    traj = filtered_trajarr[:, i*2:i*2+2]    
    msd_vals[:, i], msd_counts[:, i] = MSD(traj, MSD_pts)
    
MSD_filepath = create_saveto_filepath(filename, '_MSD_values.csv')
MSD_count_filepath = create_saveto_filepath(filename, '_MSD_counts.csv')
np.savetxt(MSD_filepath, msd_vals, delimiter=',')
np.savetxt(MSD_count_filepath, msd_counts, delimiter=',')

# Calculate Dmsd Fits
print("Calculating DMSD fits...\n")
Dmsd_arr = np.zeros((goodtrajct, 3)) # Dmsd, intercept and R^2
Dmsd_arr = DMSD(msd_vals, MSD_pts, tbf, folder)

Dmsd_filepath = create_saveto_filepath(filename, '_DMSD_fit_results.csv')
np.savetxt(Dmsd_filepath, Dmsd_arr, delimiter=',', header='Dmsd, R^2')

# Calculate QE Dmsd
QE_Dmsd(msd_vals, MSD_pts)

# Calculate Rg and a2
print("Calculating Rg and a2...\n")
Rg_a2_arr = np.zeros((goodtrajct, 3)) # Rg and a2 values
tensor_calcarr = np.zeros((goodtrajct, 5))

for i in range(goodtrajct):
    traj = filtered_trajarr[:, i*2:i*2+2]
    trajlen = trajinfo[i, 1]    
    temp_arr = Rg_a2_calc(traj, tbf, t_tot)
    Rg_a2_arr[i, :] = temp_arr[0:3]
    tensor_calcarr[i, :] = temp_arr[3:]
    
Rg_a2_filepath = create_saveto_filepath(filename, '_Rg_a2_results.csv')
tensorcalc_filepath = create_saveto_filepath(filename, '_Rg_tensor_vals.csv')
np.savetxt(Rg_a2_filepath, Rg_a2_arr, delimiter=',', header='Rg, Rg_norm, a2')
np.savetxt(tensorcalc_filepath, tensor_calcarr, delimiter=',', header="R1^2, R2^2, N")

# Cleanup and output results
output_results(Dmsd_arr, Rg_a2_arr, filtered_trajarr, goodtrajct, folder)

QE_Dmsd(msd_vals, MSD_pts)

print('Calculation Complete!')